# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Muziekvereniging "De Volharding"
subtitle: Opgericht 1964
description:

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devolhardingduizel.nl" # the base hostname & protocol for your site, e.g. http://example.com
locale: "nl"

author: Muziekvereniging De Volharding

socials:
  facebook: https://www.facebook.com/VolhardingDuizel
  youtube: https://www.youtube.com/channel/UCryjNmj1ofsllUkEbGT6PFQ

include:
  - _pages

color:
  primary: "#4b4375"
  secondary: "#c1bcd5"
  success: "#6baa79"
  info: "#81aebc"
  warning: "#a79d2b"
  danger: "#b55955"
  light: "#f5f6f7"
  dark: "#0a0908"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom
contact:
  name: Muziekvereniging "De Volharding"
  email: info@devolhardingduizel.nl
  address: Akkerstraat 16
  postal: 5525 AC
  city: Duizel
  phone: 06-25437761
